import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { getPages } from "@/sanity/sanity-utils";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Personal Website",
  description: "Generated by create next app and sanity.io",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className={`${inter.className} max-w-5xl py-10 mx-auto`}>
        <header className="flex items-center justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-500 text-transparent bg-clip-text text-lg font-bold"
          >
            Babina
          </Link>
          <div className="flex items-center text-sm text-gray-600 gap-5">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
